package main.enums;

/**
 * Enumeration for various types of validators based on the rules scenarios
 */
public enum ValidatorTypes {

    NONE,
    UNIT_TOKEN_VALIDATOR,
    ROMAN_NUMERAL_C_OCCURRENCE_VALIDATOR,
    ROMAN_NUMERAL_D_OCCURRENCE_VALIDATOR,
    ROMAN_NUMERAL_I_OCCURRENCE_VALIDATOR,
    ROMAN_NUMERAL_L_OCCURRENCE_VALIDATOR,
    ROMAN_NUMERAL_M_OCCURRENCE_VALIDATOR,
    ROMAN_NUMERAL_V_OCCURRENCE_VALIDATOR,
    ROMAN_NUMERAL_X_OCCURRENCE_VALIDATOR,
    ROMAN_NUMERAL_C_PLACEMENT_VALIDATOR,
    ROMAN_NUMERAL_I_PLACEMENT_VALIDATOR,
    ROMAN_NUMERAL_X_PLACEMENT_VALIDATOR,
    ROMAN_NUMERAL_SYMBOL_VALIDATOR,

}
